name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ci_test_user
          POSTGRES_PASSWORD: ci_test_password
          POSTGRES_DB: ci_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ci_test_user -d ci_test_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
          --network-alias localhost

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run tests
        env:
          # This now correctly uses the 'localhost' alias we created above
          SQLALCHEMY_DATABASE_URL: postgresql+psycopg2://ci_test_user:ci_test_password@localhost:5432/ci_test_db
          
          # PGPASSWORD is set for the pg_isready utility
          PGPASSWORD: ci_test_password 
          
          JWT_SECRET_KEY: "super-secret-ci-key"
          JWT_ALGORITHM: "HS256"
          FINNHUB_API_KEY: "dummy-finnhub-key"
          EMAIL_FROM_ADDRESS: "ci@test.com"
          S3_BUCKET_NAME: "ci-test-bucket"
          AWS_ACCESS_KEY_ID: "dummy-key-id"
          AWS_SECRET_ACCESS_KEY: "dummy-secret-key"
          AWS_REGION_NAME: "us-east-1"
        run: |
          echo "Waiting for Postgres to start..."
          
          # FIX 2: Use the 'localhost' alias here as well, along with explicit port (-p)
          for i in {1..15}; do
            pg_isready -h localhost -p 5432 -U ci_test_user && break
            echo "Postgres not ready yet ($i/15)..."
            sleep 3
          done
          
          # Final check before continuing
          pg_isready -h localhost -p 5432 -U ci_test_user || (echo "Postgres failed to start" && exit 1)

          # 3. Run Pytest
          echo "Running tests..."
          
          pytest -v